name: 'Update types'

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'

      - run: npm ci
      - run: npm run update -- --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
